"""
Tools — Code Generation
=========================
Jinja2 template rendering for FastAPI service scaffolding.
Applies black/isort formatting post-generation.
"""

import logging
import py_compile
import tempfile
import os
from pathlib import Path
from typing import Dict, List, Optional

from jinja2 import Environment, BaseLoader

logger = logging.getLogger("tools.code_generation")


# ══════════════════════════════════════════════
#  FASTAPI SERVICE TEMPLATE
# ══════════════════════════════════════════════

FASTAPI_SERVICE_TEMPLATE = '''"""
{{ service_name | title | replace("-", " ") }} — FastAPI Microservice
{{ "=" * (service_name | length + 30) }}
Auto-generated by Architecture Migration Assistant.
"""

from fastapi import FastAPI, HTTPException, Depends, status
from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime, Boolean
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, Session
from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime
import logging

# ── App Setup ──
app = FastAPI(
    title="{{ service_name }}",
    version="1.0.0",
    description="Migrated from legacy monolith"
)

logger = logging.getLogger("{{ service_name }}")

# ── Database Setup ──
SQLALCHEMY_DATABASE_URL = "sqlite:///./{{ service_name | replace("-", "_") }}.db"
engine = create_engine(SQLALCHEMY_DATABASE_URL, connect_args={"check_same_thread": False})
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


def get_db():
    """Database session dependency."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

{% for model in models %}
# ── {{ model.name }} ORM Model ──
class {{ model.name }}Model(Base):
    """SQLAlchemy ORM model for {{ model.table_name }}."""
    __tablename__ = "{{ model.table_name }}"
    {% for col in model.columns %}
    {{ col.name }} = Column({{ col.type }}{% if col.primary_key %}, primary_key=True{% endif %}{% if col.unique %}, unique=True{% endif %}{% if col.nullable == False %}, nullable=False{% endif %}{% if col.default %}, default={{ col.default }}{% endif %})
    {% endfor %}


class {{ model.name }}Schema(BaseModel):
    """Pydantic schema for {{ model.name }}."""
    {% for field in model.schema_fields %}
    {{ field.name }}: {{ field.type }}{% if field.optional %} = None{% endif %}
    {% endfor %}

    class Config:
        from_attributes = True

{% endfor %}

# Create tables
Base.metadata.create_all(bind=engine)

{% for endpoint in endpoints %}
@app.{{ endpoint.method | lower }}(
    "{{ endpoint.path }}",
    {% if endpoint.response_model %}response_model={{ endpoint.response_model }},{% endif %}
    status_code=status.{{ endpoint.status_code | default("HTTP_200_OK") }}
)
async def {{ endpoint.function_name }}(
    {% for param in endpoint.params %}
    {{ param.name }}: {{ param.type }}{% if param.default %} = {{ param.default }}{% endif %},
    {% endfor %}
    db: Session = Depends(get_db)
):
    """{{ endpoint.docstring | default("Auto-generated endpoint.") }}"""
    {{ endpoint.body | indent(4) }}

{% endfor %}

@app.get("/health")
async def health_check():
    """Service health check."""
    return {"status": "healthy", "service": "{{ service_name }}"}
'''


PYTEST_TEMPLATE = '''"""
Tests for {{ service_name }}
{{ "=" * (service_name | length + 12) }}
Auto-generated by Architecture Migration Assistant.
"""

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from {{ service_name | replace("-", "_") }}_service import app, Base, get_db


SQLALCHEMY_DATABASE_URL = "sqlite:///./test_{{ service_name | replace("-", "_") }}.db"
engine = create_engine(SQLALCHEMY_DATABASE_URL, connect_args={"check_same_thread": False})
TestingSessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


@pytest.fixture(autouse=True)
def setup_db():
    """Create fresh database for each test."""
    Base.metadata.create_all(bind=engine)
    yield
    Base.metadata.drop_all(bind=engine)


@pytest.fixture
def client():
    """Test client with DB override."""
    def override_get_db():
        db = TestingSessionLocal()
        try:
            yield db
        finally:
            db.close()

    app.dependency_overrides[get_db] = override_get_db
    yield TestClient(app)
    app.dependency_overrides.clear()


{% for test in test_cases %}
def {{ test.name }}(client):
    """{{ test.docstring | default("Auto-generated test.") }}"""
    {{ test.body | indent(4) }}

{% endfor %}
'''


# ══════════════════════════════════════════════
#  TEMPLATE RENDERING
# ══════════════════════════════════════════════

def render_service(service_name: str, models: List[Dict], endpoints: List[Dict]) -> str:
    """Render a FastAPI service from template.

    Args:
        service_name: Name of the service (e.g., 'user-service')
        models: List of model definitions
        endpoints: List of endpoint definitions

    Returns:
        Generated Python source code string
    """
    env = Environment(loader=BaseLoader())
    template = env.from_string(FASTAPI_SERVICE_TEMPLATE)

    code = template.render(
        service_name=service_name,
        models=models,
        endpoints=endpoints,
    )

    return code


def render_tests(service_name: str, test_cases: List[Dict]) -> str:
    """Render pytest test suite from template."""
    env = Environment(loader=BaseLoader())
    template = env.from_string(PYTEST_TEMPLATE)

    code = template.render(
        service_name=service_name,
        test_cases=test_cases,
    )

    return code


# ══════════════════════════════════════════════
#  POST-PROCESSING
# ══════════════════════════════════════════════

def format_code(code: str) -> str:
    """Apply black and isort formatting to generated code.

    Falls back to original code if formatters aren't available.
    """
    formatted = code

    # Apply isort
    try:
        import isort
        formatted = isort.code(formatted)
    except ImportError:
        logger.warning("isort not available, skipping import sorting")

    # Apply black
    try:
        import black
        mode = black.Mode(line_length=100)
        formatted = black.format_str(formatted, mode=mode)
    except ImportError:
        logger.warning("black not available, skipping formatting")
    except Exception as e:
        logger.warning(f"black formatting failed: {e}")

    return formatted


def validate_syntax(code: str) -> bool:
    """Validate Python syntax using py_compile.

    Per CONTEXT.md: py_compile gate before Test-Gen handoff.
    """
    with tempfile.NamedTemporaryFile(mode="w", suffix=".py", delete=False, encoding="utf-8") as f:
        f.write(code)
        f.flush()
        temp_path = f.name

    try:
        py_compile.compile(temp_path, doraise=True)
        return True
    except py_compile.PyCompileError as e:
        logger.error(f"Syntax validation failed: {e}")
        return False
    finally:
        os.unlink(temp_path)
